/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CalculateInterestDAO;
import DTO.PassBookSearch;
import Utility.StringUtility;
import static java.lang.String.format;
import static java.lang.String.format;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cogia_grk2dkj
 */
public class CalculateInterestSearchView extends javax.swing.JFrame {

    private ArrayList<PassBookSearch> list;

    /**
     * Creates new form CalculateInterestSearchView
     */
    public CalculateInterestSearchView() {
        initComponents();
        list = new ArrayList<>();
    }

    public void loadList() {

        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        String[] colName = {"Số Tài Khoản", "CMTND", "Mã Sổ Tiết Kiệm", "Gốc", "Loại Sổ", "Kỳ Hạn", "Lãi Xuất/năm (%)", "Ngày Mở"};
        dtm.setColumnIdentifiers(colName);

        for (int i = 0; i < list.size(); i++) {
            Object[] objs = {list.get(i).getSoTaiKhoan(), list.get(i).getCMTND(), list.get(i).getMaSOTietKiem(), String.format("%.0f", list.get(i).getGoc()), list.get(i).getLoaiSo(),
                list.get(i).getKyhan(), list.get(i).getLaiXuat(), list.get(i).getNgayMo()};
            dtm.addRow(objs);
        }
        jTbSearchResults.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTFSearchInput = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jRBSTK = new javax.swing.JRadioButton();
        jRBCMND = new javax.swing.JRadioButton();
        jBtnXemLai = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbSearchResults = new javax.swing.JTable();

        buttonGroup1.add(jRBSTK);
        buttonGroup1.add(jRBCMND);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm kiếm thông tin Sổ TK");

        jTFSearchInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTFSearchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSearchInputActionPerformed(evt);
            }
        });

        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jRBSTK.setText("STK");
        jRBSTK.setSelected(true);
        jRBSTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSTKActionPerformed(evt);
            }
        });

        jRBCMND.setText("CMND");

        jBtnXemLai.setText("Xem lãi");
        jBtnXemLai.setEnabled(false);
        jBtnXemLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXemLaiActionPerformed(evt);
            }
        });

        jBtnCancel.setText("Trở lại");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jTbSearchResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Số Tài Khoản", "CMND", "Mã sổ tiết kiệm", "Gốc", "Loại Sổ", "Kỳ Hạn", "Lãi xuất/năm (%)", "Ngày mở"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbSearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbSearchResultsMouseClicked(evt);
            }
        });
        jTbSearchResults.setVisible(false);
        jScrollPane1.setViewportView(jTbSearchResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRBSTK)
                        .addGap(18, 18, 18)
                        .addComponent(jRBCMND))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBtnXemLai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSTK)
                    .addComponent(jRBCMND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnXemLai)
                    .addComponent(jBtnCancel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed

        if (jTFSearchInput.getText().equals("")) {
            JOptionPane.showMessageDialog(this, StringUtility.NOT_EMPTY_SEARCH_KEY_INPUT);
        } else {
            String string = jTFSearchInput.getText();
            try {
                Double num = Double.parseDouble(string);
            } catch (NumberFormatException e) {
                System.out.println("khong phai la so");
                JOptionPane.showMessageDialog(this, StringUtility.INPUT_ONLY_NUMBER);
                return;
            }
            int type = 0;
            if (jRBCMND.isSelected()) {
                type = 1;
            } else {
                type = 0;
            }
            list = new CalculateInterestDAO().search(jTFSearchInput.getText().trim(), type);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, StringUtility.RESULT_EMPTY);
            }
            loadList();
            jTbSearchResults.setVisible(true);
        }
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jRBSTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBSTKActionPerformed

    private void jTFSearchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSearchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSearchInputActionPerformed

    private void jTbSearchResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbSearchResultsMouseClicked
        jBtnXemLai.setEnabled(true);
    }//GEN-LAST:event_jTbSearchResultsMouseClicked

    private void jBtnXemLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXemLaiActionPerformed
        PassBookSearch pbs = new PassBookSearch();
        int rowselect = jTbSearchResults.getSelectedRow();
        pbs.setCMTND((String) jTbSearchResults.getValueAt(rowselect, 1));
        pbs.setGoc(Double.parseDouble((String) jTbSearchResults.getValueAt(rowselect, 3)));
        pbs.setKyhan((int) jTbSearchResults.getValueAt(rowselect, 5));
        pbs.setLaiXuat((double) jTbSearchResults.getValueAt(rowselect, 6));
        pbs.setLoaiSo((String) jTbSearchResults.getValueAt(rowselect, 4));
        pbs.setMaSOTietKiem((int) jTbSearchResults.getValueAt(rowselect, 2));
        pbs.setSoTaiKhoan((int) jTbSearchResults.getValueAt(rowselect, 0));
        pbs.setNgayMo((Timestamp) jTbSearchResults.getValueAt(rowselect, 7));

        new CalculateInterestResultView(pbs).setVisible(true);

    }//GEN-LAST:event_jBtnXemLaiActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateInterestSearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnXemLai;
    private javax.swing.JRadioButton jRBCMND;
    private javax.swing.JRadioButton jRBSTK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFSearchInput;
    private javax.swing.JTable jTbSearchResults;
    // End of variables declaration//GEN-END:variables
}
