/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DTO.PassBookSearch;
import Utility.StringUtility;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author cogia_grk2dkj
 */
public class CalculateInterestResultView extends javax.swing.JFrame {

    private PassBookSearch pbs;

    /**
     * Creates new form CalculateInterestResultView
     */
    public CalculateInterestResultView() {
        initComponents();
    }

    public CalculateInterestResultView(PassBookSearch pbs) {
        initComponents();
        this.pbs = pbs;
        loadData();
    }

    public void loadData() {
        if (pbs == null) {
            return;
        }

        jLbCMTND.setText(pbs.getCMTND());
        jLbGoc.setText(String.format("%.3f", pbs.getGoc()));
        //jLbInterest.setText(pbs.get);
        jLbKyHan.setText(String.valueOf(pbs.getKyhan()));
        jLbLoaiSo.setText(pbs.getLoaiSo());
        jLbLaiXuat1Nam.setText(String.valueOf(pbs.getLaiXuat()));
        //jLbNgayDaoHan.setText(pbs.g);
        jLbSTK.setText(String.valueOf(pbs.getSoTaiKhoan()));
        jLbSoSoTK.setText(String.valueOf(pbs.getMaSOTietKiem()));
//     DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  

        //jLbNgayMo.setText(dateFormat.format(pbs.getNgayMo()));
        System.out.println("ky han:" + pbs.getKyhan());
        jLbNgayMo.setText(pbs.getNgayMo().toString());

        Calendar cal = Calendar.getInstance();
        cal.setTimeInMillis(pbs.getNgayMo().getTime());
        cal.add(Calendar.MONTH, pbs.getKyhan());
        Timestamp ngaydaohan = new Timestamp(cal.getTimeInMillis());
        jLbNgayDaoHan.setText(ngaydaohan.toString());
        double lai = TinhLai(pbs);
        jLbInterest.setText(String.format("%.3f", lai));
    }

    public double TinhLai(PassBookSearch pbs) {
        Calendar cal = Calendar.getInstance();
        double lai = 0;
        int ngay = Math.round((cal.getTimeInMillis() - pbs.getNgayMo().getTime()) / (1000 * 60 * 60 * 24));
        System.out.println("Ngay:" + ngay);
        if (pbs.getLoaiSo().equalsIgnoreCase("KKH")) {
            lai = ((double) pbs.getGoc()) * ((double) ngay / 360) * (StringUtility.LAI_XUAT_KKH / 100);
        } else {
            if (ngay < (pbs.getKyhan() * 30)) {
                lai = ((double) pbs.getGoc()) * ((double) ngay / 360) * (StringUtility.LAI_XUAT_KKH  / 100);
            } else {
                double laidaohan = ((double) pbs.getGoc()) * ((double) pbs.getLaiXuat() / 100);
                double laiquahan = ((double) pbs.getGoc() + laidaohan) * (StringUtility.LAI_XUAT_KKH  / 100) * ((double) (ngay - pbs.getKyhan() * 30) / 360);
                System.out.println("laidaohan:" + laidaohan + ", laiquahan:" + laiquahan);
                lai = laidaohan + laiquahan;
            }
            System.out.println("lai:" + lai);
        }

        return lai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLbInterest = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLbSTK = new javax.swing.JLabel();
        jLbCMTND = new javax.swing.JLabel();
        jLbSoSoTK = new javax.swing.JLabel();
        jLbGoc = new javax.swing.JLabel();
        jLbLoaiSo = new javax.swing.JLabel();
        jLbNgayMo = new javax.swing.JLabel();
        jLbKyHan = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLbNgayDaoHan = new javax.swing.JLabel();
        jBtnRut = new javax.swing.JButton();
        jBtnTroLai = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLbLaiXuat1Nam = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lãi Xuất");

        jLabel1.setText("STK:");

        jLabel3.setText("CMTND:");

        jLabel4.setText("Mã Sổ TK:");

        jLabel5.setText("Loại sổ:");

        jLabel6.setText("Ngày Mở:");

        jLabel7.setText("Kỳ Hạn:");

        jLabel8.setText("Lãi nếu rút tới hiện tại:");

        jLbInterest.setText("<Lãi>");

        jLabel9.setText("Gốc:");

        jLbSTK.setText("<STK>");

        jLbCMTND.setText("<CMTND>");

        jLbSoSoTK.setText("<Mã Sổ TK>");

        jLbGoc.setText("<Số tiền gốc>");

        jLbLoaiSo.setText("<Loại Sổ CKH/KKH>");

        jLbNgayMo.setText("<Ngày Mở>");

        jLbKyHan.setText("<Kỳ Hạn BN Tháng>");

        jLabel10.setText("Ngày Đáo Hạn:");

        jLbNgayDaoHan.setText("<Ngày đáo hạn>");

        jBtnRut.setText("Rút");

        jBtnTroLai.setText("Trở lại");
        jBtnTroLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTroLaiActionPerformed(evt);
            }
        });

        jLabel11.setText("Lai xuat:");

        jLbLaiXuat1Nam.setText("<Lai Xuat/nam>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jBtnRut)
                .addGap(35, 35, 35)
                .addComponent(jBtnTroLai)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLbNgayDaoHan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbSTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbCMTND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbSoSoTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbGoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbLoaiSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbNgayMo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLbKyHan, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jLbLaiXuat1Nam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLbSTK))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLbCMTND))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLbSoSoTK))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLbGoc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLbLoaiSo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLbNgayMo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLbKyHan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLbLaiXuat1Nam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLbNgayDaoHan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLbInterest))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRut)
                    .addComponent(jBtnTroLai))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTroLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTroLaiActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnTroLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateInterestResultView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateInterestResultView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRut;
    private javax.swing.JButton jBtnTroLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbCMTND;
    private javax.swing.JLabel jLbGoc;
    private javax.swing.JLabel jLbInterest;
    private javax.swing.JLabel jLbKyHan;
    private javax.swing.JLabel jLbLaiXuat1Nam;
    private javax.swing.JLabel jLbLoaiSo;
    private javax.swing.JLabel jLbNgayDaoHan;
    private javax.swing.JLabel jLbNgayMo;
    private javax.swing.JLabel jLbSTK;
    private javax.swing.JLabel jLbSoSoTK;
    // End of variables declaration//GEN-END:variables


}
